# yml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Sync Labels
on:
  push:
    branches: [master]
  pull_request:
    paths: [".github/labels.yml"]
  workflow_dispatch:
jobs:
  sync:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    permissions: { contents: read, issues: write }
    steps:
      - uses: actions/checkout@v6
      - uses: kjanat/github-labelmanager@v1
        with: { token: "${{ github.token }}" }
